### ISSUE TITLE
show inactives checked on custom records

### ISSUE THREAD

**Issue by usulix** [suiteplus/ns-export#3]
Error : 
TypeError: 'undefined' is not an object (evaluating 'row.find('td:nth-child(1) a').attr('href').match')

Reproduce : 
- log in to Netsuite GUI
- visit /app/common/custom/custrecords.nl?whence=
- check box for show inactives
- run nsexport
- see error at Load Records

Details : 
checking box adds column to table for the inactive checkbox and throws off selectors in html scrape

Fix :
check if column exists and adjust selectors if it is on the page

Pull Request : 
I will try to get a patch put together and submitted (I mean pull request....)

**Comment by danieljoppi** [comment]
You need inactive records?

We can add some extra parameter to show inactive, example: `nsexport * --show-incative`.

What you think?
